---
authors:
  - Jeff Groom
dependencies:
  ansible.netcommon: '>=1.0.0'
license_file: LICENSE
version: 1.0.1
name: saos8
namespace: ciena
readme: README.md
repository: https://github.com/ciena/ciena.saos8
tags: [ciena, saos, networking, ethernet]
